# For use with development
version: "3.8"
services:
  db:
    image: maria-db:10.4

    volumes:
      - db-data:/var/lib/mysql
      - type: bind
        source: ./db-init
        target: /docker-entrypoint-initdb.d
    networks:
      - backend
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
