# For use with development
version: "3.8"
services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: languagechallenge
      MYSQL_ROOT_PASSWORD:
    volumes:
      - db-data:/var/lib/mysql
      - type: bind
        source: ./db-init
        target: /docker-entrypoint-initdb.d
    networks:
      - backend
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - type: bind
        source: .
        target: /var/www/html

networks:
  backend:

volumes:
  db-data:
